import {
  IncidentAlert,
  RiskZone,
  HotspotMarker,
  OfficerProfile,
  SystemNotificationSettings,
  SystemDiagnostics,
} from '../types';

export const INITIAL_OFFICER_PROFILE: OfficerProfile = {
  name: 'Commander Alex Vance',
  badgeId: 'FS-88392-AP',
  rank: 'Senior Forestry Inspector',
  assignedSector: 'Sector 4 - Northern Range',
  email: 'a.vance@forestry.firesense.gov',
  phone: '+1 (555) 492-7710',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  clearanceLevel: 'DEFCON-1 Regional Incident Commander',
  joinedYear: 2018,
  stationBase: 'Cascade Range Command Hub, Station 12',
};

export const INITIAL_NOTIFICATION_SETTINGS: SystemNotificationSettings = {
  smsAlerts: true,
  mobilePush: true,
  emailBroadcast: true,
  autoDispatchTriggers: false,
  audioSiren: true,
  droneAutoRecon: true,
  evacuationWarningRelay: true,
};

export const SYSTEM_DIAGNOSTICS_DATA: SystemDiagnostics = {
  weatherApiStatus: 'Online',
  satelliteFeedStatus: 'Connected',
  satelliteName: 'VIIRS (NOAA-20) / Copernicus Sentinel-3',
  sensorGridCoverage: 98.4,
  systemUptime: 99.98,
  latencyMs: 42,
  activeSensorsCount: 1420,
  lastSyncTime: '12 seconds ago',
};

// Map centered around a majestic forest mountainous region (Pacific Northwest / Sierra range style, lat: 44.15, lng: -121.75)
export const MAP_CENTER: [number, number] = [44.168, -121.745];

export const MOCK_RISK_ZONES: RiskZone[] = [
  {
    id: 'zone-extreme-1',
    name: 'Pine Ridge & Upper Crest',
    sectorCode: 'Sector 7',
    riskLevel: 'extreme',
    riskScore: 89,
    center: [44.185, -121.725],
    areaSqKm: 42.5,
    moistureIndex: 11.2,
    fuelLoad: 'Heavy dry timber & needle litter (14 tons/acre)',
    lastSatellitePass: '4 mins ago (VIIRS Thermal Band I4)',
    coordinates: [
      [44.205, -121.755],
      [44.212, -121.710],
      [44.180, -121.685],
      [44.162, -121.715],
      [44.175, -121.760],
    ],
  },
  {
    id: 'zone-high-1',
    name: 'Valley Basin & Creek Gulch',
    sectorCode: 'Sector 3',
    riskLevel: 'high',
    riskScore: 74,
    center: [44.145, -121.795],
    areaSqKm: 58.0,
    moistureIndex: 18.5,
    fuelLoad: 'Dry chaparral, brush and fallen pine needles',
    lastSatellitePass: '9 mins ago (Sentinel-3 SLSTR)',
    coordinates: [
      [44.165, -121.835],
      [44.172, -121.770],
      [44.135, -121.755],
      [44.118, -121.800],
      [44.130, -121.845],
    ],
  },
  {
    id: 'zone-moderate-1',
    name: 'Blackwood Canyon Highlands',
    sectorCode: 'Sector 12',
    riskLevel: 'moderate',
    riskScore: 48,
    center: [44.120, -121.705],
    areaSqKm: 64.2,
    moistureIndex: 32.0,
    fuelLoad: 'Mixed conifer & deciduous undergrowth',
    lastSatellitePass: '15 mins ago (MODIS Terra)',
    coordinates: [
      [44.140, -121.735],
      [44.148, -121.670],
      [44.105, -121.650],
      [44.095, -121.715],
      [44.112, -121.745],
    ],
  },
  {
    id: 'zone-low-1',
    name: 'Emerald River Valley & Lakefront',
    sectorCode: 'Sector 1',
    riskLevel: 'low',
    riskScore: 18,
    center: [44.200, -121.810],
    areaSqKm: 82.1,
    moistureIndex: 58.4,
    fuelLoad: 'Hydrated riparian foliage and moist riverbed',
    lastSatellitePass: '18 mins ago (Sentinel-2 MSI)',
    coordinates: [
      [44.225, -121.845],
      [44.230, -121.785],
      [44.185, -121.775],
      [44.175, -121.830],
      [44.195, -121.860],
    ],
  },
];

export const MOCK_HOTSPOTS: HotspotMarker[] = [
  {
    id: 'hs-1',
    name: 'Hotspot HS-Alpha-7',
    sector: 'Sector 7 (Pine Ridge)',
    coordinates: [44.188, -121.722],
    riskLevel: 'extreme',
    thermalReadingC: 48.6,
    confidence: 96,
    satelliteSource: 'VIIRS-NOAA20',
    activeFlame: true,
  },
  {
    id: 'hs-2',
    name: 'Hotspot HS-Bravo-3',
    sector: 'Sector 3 (Valley Basin)',
    coordinates: [44.148, -121.790],
    riskLevel: 'high',
    thermalReadingC: 42.1,
    confidence: 88,
    satelliteSource: 'Copernicus-Sentinel3',
    activeFlame: false,
  },
  {
    id: 'hs-3',
    name: 'Hotspot HS-Charlie-12',
    sector: 'Sector 12 (Blackwood Canyon)',
    coordinates: [44.118, -121.700],
    riskLevel: 'moderate',
    thermalReadingC: 34.5,
    confidence: 72,
    satelliteSource: 'MODIS-Terra',
    activeFlame: false,
  },
];

export const INITIAL_ALERTS: IncidentAlert[] = [
  {
    id: 'alert-4092',
    alertNumber: '#4092',
    title: 'Alert #4092 - Pine Ridge Sector 7',
    sector: 'Sector 7 (Pine Ridge)',
    riskLevel: 'extreme',
    riskScore: 89,
    status: 'active',
    timestamp: '3 mins ago (14:22:15 UTC)',
    coordinates: [44.188, -121.722],
    elevationMeters: 1420,
    weather: {
      temperature: 41.2,
      humidity: 14,
      windSpeed: 28,
      windDirection: 'SSE',
      windDegrees: 155,
      rainfall: 0.0,
      uvIndex: 9.8,
      droughtFactor: 9.2,
    },
    prediction: {
      directionText: 'Spreading North-East at 14 km/h towards Ridge Trail',
      speedKmh: 14,
      targetLandmark: 'Ridge Trail & Lookout Point',
      propagationRisk: 'Rapid',
      hoursToCriticalBoundary: 2.5,
      projectedAreaHectares: 185,
      containmentProbability: 34,
    },
    nearestStations: [
      {
        id: 'st-alpha',
        name: 'Squad Alpha Base',
        distanceKm: 3.4,
        status: 'Ready',
        personnelCount: 18,
        engineTypes: ['Type 3 Wildland Engine (2x)', 'Water Tender 1500gal', 'All-Terrain BullDozer'],
        contactRadio: 'Channel 4 Tactical (154.280 MHz)',
      },
      {
        id: 'st-central',
        name: 'Central Forestry Station',
        distanceKm: 7.8,
        status: 'On Standby',
        personnelCount: 32,
        engineTypes: ['Type 1 Structural (1x)', 'Type 4 Brush Patrol (3x)', 'Air Attack Command Van'],
        contactRadio: 'Channel 1 Dispatch (151.175 MHz)',
      },
      {
        id: 'st-helitack',
        name: 'Cascade Helitack Wing',
        distanceKm: 12.0,
        status: 'Ready',
        personnelCount: 8,
        engineTypes: ['Bell 212 Water Dropper (600gal)', 'Super Puma Helitanker'],
        contactRadio: 'Air-to-Ground VHF (122.925 MHz)',
      },
    ],
    nearestWaterSources: [
      {
        id: 'w-serene',
        name: 'Lake Serene Reservoir',
        distanceKm: 1.2,
        direction: 'North',
        type: 'Reservoir',
        capacityPercent: 85,
        flowRate: 'High',
        heliBucketAccessible: true,
      },
      {
        id: 'w-pine-creek',
        name: 'Pine Creek Water Supply',
        distanceKm: 3.5,
        direction: 'East',
        type: 'Creek',
        capacityPercent: 70,
        flowRate: 'High',
        heliBucketAccessible: false,
      },
      {
        id: 'w-high-tank',
        name: 'High Ridge Storage Cistern #4',
        distanceKm: 2.1,
        direction: 'West',
        type: 'Hydrant Tank',
        capacityPercent: 95,
        flowRate: 'Static',
        heliBucketAccessible: false,
      },
    ],
    aiSummary:
      'Due to high temperature (41.2°C), critically low humidity (14%), and elevated SSE winds (28 km/h), there is a high probability for ignition and rapid flame propagation within the next 3 hours toward Ridge Trail.',
    reportedBy: 'AI Thermal Satellite Feed (VIIRS Pass 882) + Autonomous Ground Sensor Grid Node #074',
    smokeDensity: 'Dense',
    fuelType: 'Dry Pine Conifer',
  },
  {
    id: 'alert-4091',
    alertNumber: '#4091',
    title: 'Alert #4091 - Valley Basin Sector 3',
    sector: 'Sector 3 (Valley Basin)',
    riskLevel: 'high',
    riskScore: 74,
    status: 'pending',
    timestamp: '18 mins ago (14:07:40 UTC)',
    coordinates: [44.148, -121.790],
    elevationMeters: 980,
    weather: {
      temperature: 38.6,
      humidity: 19,
      windSpeed: 22,
      windDirection: 'SW',
      windDegrees: 225,
      rainfall: 0.0,
      uvIndex: 8.5,
      droughtFactor: 7.8,
    },
    prediction: {
      directionText: 'Spreading North-North-East at 9 km/h towards Basin Campgrounds',
      speedKmh: 9,
      targetLandmark: 'Basin Campgrounds & Creek Bridge',
      propagationRisk: 'Moderate',
      hoursToCriticalBoundary: 4.8,
      projectedAreaHectares: 95,
      containmentProbability: 58,
    },
    nearestStations: [
      {
        id: 'st-basin',
        name: 'Valley Rapid Response Unit',
        distanceKm: 2.8,
        status: 'Ready',
        personnelCount: 12,
        engineTypes: ['Brush Pumper 4x4 (2x)', 'Rapid Scout Buggy'],
        contactRadio: 'Channel 3 Local (153.950 MHz)',
      },
      {
        id: 'st-alpha',
        name: 'Squad Alpha Base',
        distanceKm: 6.2,
        status: 'Ready',
        personnelCount: 18,
        engineTypes: ['Type 3 Wildland Engine', 'Water Tender'],
        contactRadio: 'Channel 4 Tactical (154.280 MHz)',
      },
    ],
    nearestWaterSources: [
      {
        id: 'w-basin-creek',
        name: 'Valley Gulch River Standpipe',
        distanceKm: 0.8,
        direction: 'South-West',
        type: 'River',
        capacityPercent: 90,
        flowRate: 'High',
        heliBucketAccessible: true,
      },
      {
        id: 'w-basin-pond',
        name: 'Campground Retention Pond',
        distanceKm: 2.3,
        direction: 'North',
        type: 'Lake',
        capacityPercent: 62,
        flowRate: 'Static',
        heliBucketAccessible: true,
      },
    ],
    aiSummary:
      'Thermal anomalies detected near western chaparral slopes. Ground moisture at 18.5% is drying rapidly under 38.6°C heat with rising South-Westerly gusts.',
    reportedBy: 'Copernicus Sentinel-3 Thermal Infrared sensor + Drone Patrol Recon-B',
    smokeDensity: 'Moderate',
    fuelType: 'Chaparral Shrub',
  },
  {
    id: 'alert-4088',
    alertNumber: '#4088',
    title: 'Alert #4088 - Blackwood Canyon Sector 12',
    sector: 'Sector 12 (Blackwood Canyon)',
    riskLevel: 'moderate',
    riskScore: 48,
    status: 'dispatched',
    timestamp: '42 mins ago (13:43:10 UTC)',
    coordinates: [44.118, -121.700],
    elevationMeters: 1150,
    weather: {
      temperature: 33.4,
      humidity: 28,
      windSpeed: 16,
      windDirection: 'NW',
      windDegrees: 315,
      rainfall: 0.0,
      uvIndex: 7.2,
      droughtFactor: 5.4,
    },
    prediction: {
      directionText: 'Moving South-East at 5 km/h along rocky gorge corridor',
      speedKmh: 5,
      targetLandmark: 'Blackwood Creek Crossing',
      propagationRisk: 'Slow',
      hoursToCriticalBoundary: 8.0,
      projectedAreaHectares: 35,
      containmentProbability: 82,
    },
    nearestStations: [
      {
        id: 'st-south',
        name: 'South Ridge Outpost',
        distanceKm: 4.1,
        status: 'Deployed',
        personnelCount: 10,
        engineTypes: ['Wildland Patrol Unit', 'Chainsaw Sawmill Crew'],
        contactRadio: 'Channel 2 Field (152.050 MHz)',
      },
    ],
    nearestWaterSources: [
      {
        id: 'w-blackwood',
        name: 'Blackwood Dam Spillway',
        distanceKm: 1.7,
        direction: 'East',
        type: 'Reservoir',
        capacityPercent: 92,
        flowRate: 'High',
        heliBucketAccessible: true,
      },
    ],
    aiSummary:
      'Controlled smoldering spot from dry lightning strike contained to 0.4 hectares. Squad Bravo already deployed and completing containment trench.',
    reportedBy: 'Automated IR Tower Camera Node #12-South',
    smokeDensity: 'Light',
    fuelType: 'Dense Timber',
    dispatchedAt: '35 mins ago',
    dispatchedUnits: ['Squad Bravo Unit 2', 'South Ridge Patrol 4x4'],
  },
  {
    id: 'alert-4085',
    alertNumber: '#4085',
    title: 'Alert #4085 - Redwood Ridge Sector 4',
    sector: 'Sector 4 (Redwood Ridge)',
    riskLevel: 'high',
    riskScore: 78,
    status: 'active',
    timestamp: '1 hour ago (13:20:00 UTC)',
    coordinates: [44.160, -121.710],
    elevationMeters: 1380,
    weather: {
      temperature: 39.8,
      humidity: 15,
      windSpeed: 25,
      windDirection: 'S',
      windDegrees: 180,
      rainfall: 0.0,
      uvIndex: 9.1,
      droughtFactor: 8.6,
    },
    prediction: {
      directionText: 'Advancing North towards Upper Timberline logging road',
      speedKmh: 12,
      targetLandmark: 'Upper Timberline Mile 14',
      propagationRisk: 'Rapid',
      hoursToCriticalBoundary: 3.2,
      projectedAreaHectares: 120,
      containmentProbability: 46,
    },
    nearestStations: [
      {
        id: 'st-alpha',
        name: 'Squad Alpha Base',
        distanceKm: 3.9,
        status: 'Ready',
        personnelCount: 18,
        engineTypes: ['Type 3 Wildland Engine', 'Water Tender 1500gal'],
        contactRadio: 'Channel 4 Tactical (154.280 MHz)',
      },
    ],
    nearestWaterSources: [
      {
        id: 'w-serene',
        name: 'Lake Serene Reservoir',
        distanceKm: 2.8,
        direction: 'North-West',
        type: 'Reservoir',
        capacityPercent: 85,
        flowRate: 'High',
        heliBucketAccessible: true,
      },
    ],
    aiSummary:
      'Continuous thermal gradient rise observed over 45 minutes. High dead-branch canopy density creates extreme crowning hazard under sustained southern winds.',
    reportedBy: 'AI Early Warning Ensemble Model v4.8',
    smokeDensity: 'Moderate',
    fuelType: 'Dry Pine Conifer',
  },
  {
    id: 'alert-4082',
    alertNumber: '#4082',
    title: 'Alert #4082 - Whispering Pines Sector 9',
    sector: 'Sector 9 (Whispering Pines)',
    riskLevel: 'moderate',
    riskScore: 52,
    status: 'pending',
    timestamp: '2 hours ago (12:15:30 UTC)',
    coordinates: [44.135, -121.770],
    elevationMeters: 1040,
    weather: {
      temperature: 34.0,
      humidity: 24,
      windSpeed: 18,
      windDirection: 'ESE',
      windDegrees: 110,
      rainfall: 0.0,
      uvIndex: 7.9,
      droughtFactor: 6.1,
    },
    prediction: {
      directionText: 'Slow drift Westward towards Whispering Creek basin',
      speedKmh: 6,
      targetLandmark: 'Whispering Creek Footbridge',
      propagationRisk: 'Moderate',
      hoursToCriticalBoundary: 6.5,
      projectedAreaHectares: 48,
      containmentProbability: 76,
    },
    nearestStations: [
      {
        id: 'st-central',
        name: 'Central Forestry Station',
        distanceKm: 5.4,
        status: 'On Standby',
        personnelCount: 32,
        engineTypes: ['Type 4 Brush Patrol (3x)'],
        contactRadio: 'Channel 1 Dispatch (151.175 MHz)',
      },
    ],
    nearestWaterSources: [
      {
        id: 'w-basin-creek',
        name: 'Whispering Creek Stream Tap',
        distanceKm: 1.1,
        direction: 'West',
        type: 'Creek',
        capacityPercent: 78,
        flowRate: 'Moderate',
        heliBucketAccessible: false,
      },
    ],
    aiSummary:
      'Moderate risk hotspot. Sensor cluster reported microclimate humidity dip with localized breeze funneling through western saddle.',
    reportedBy: 'Ground Acoustic + Smoke Sensor Node #091',
    smokeDensity: 'Light',
    fuelType: 'Mixed conifer & deciduous undergrowth',
  },
];

export const RISK_MATRIX_INFO = [
  {
    level: 'low' as const,
    name: 'Low Risk',
    color: 'emerald',
    badgeClass: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
    indicatorBg: 'bg-emerald-500',
    iconText: '🟢',
    scoreRange: '0 - 30%',
    weatherCondition: 'Stable weather conditions, optimal moisture (>40%), low ambient winds (<15 km/h).',
    actionRequired: 'Routine monitoring, baseline drone sweeps, firebreak clearing.',
  },
  {
    level: 'moderate' as const,
    name: 'Moderate Risk',
    color: 'yellow',
    badgeClass: 'bg-amber-500/10 text-amber-300 border-amber-500/30',
    indicatorBg: 'bg-amber-400',
    iconText: '🟡',
    scoreRange: '31 - 60%',
    weatherCondition: 'Moderate dryness (25-40% humidity) or mild gusty wind activity.',
    actionRequired: 'Enhanced aerial surveillance, secondary standby teams placed on alert.',
  },
  {
    level: 'high' as const,
    name: 'High Risk',
    color: 'orange',
    badgeClass: 'bg-orange-500/10 text-orange-400 border-orange-500/30',
    indicatorBg: 'bg-orange-500',
    iconText: '🟠',
    scoreRange: '61 - 80%',
    weatherCondition: 'Low humidity (15-25%), elevated temperatures (>35°C), sustained rising winds.',
    actionRequired: 'Pre-positioning mobile tankers, citizen cautionary notices, staging helitack.',
  },
  {
    level: 'extreme' as const,
    name: 'Extreme Risk',
    color: 'red',
    badgeClass: 'bg-red-500/10 text-red-400 border-red-500/30',
    indicatorBg: 'bg-red-500',
    iconText: '🔴',
    scoreRange: '81 - 100%',
    weatherCondition: 'Critical ignition threshold reached (<15% humidity, >40°C, >25 km/h winds, zero rainfall).',
    actionRequired: 'Immediate alert status, automated squad mobilization, perimeter evacuations.',
  },
];
